services:
  - type: web
    name: parser-bot
    runtime: python
    buildCommand: pip install -r requirements.txt && playwright install chromium && playwright install-deps
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
    plan: free
